import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset("tips")
df=df.dropna()
print(df.head())
print(df.info())
sns.barplot(x="day", y='total_bill', hue='sex', data=df)
plt.title('Every Bill by gender')
plt.xlabel('day')
plt.ylabel('average bill')
plt.show()
sns.countplot(x='day', hue='sex', data=df)
plt.title('number of dinners per day by gender')
plt.xlabel('day')
plt.ylabel('count')
plt.show()
sns.boxplot(x='day', y='total_bill', data=df)
plt.title('spread of total bill per day')
plt.xlabel('day')
plt.ylabel('total bill')
plt.show()
sns.stripplot(x='day', y='total_bill', data=df, jitter=True)
plt.title('every bil amoutn ber day')
plt.xlabel('day')
plt.ylabel('total bill')
plt.show()
sns.swarmplot(x='day', y='total_bill', data=df)
plt.title('every bil amoutn ber day')
plt.xlabel('day')
plt.ylabel('total bill')
plt.show()
sns.jointplot(x='total_bill', y='tip', data=df)
plt.suptitle('total bill v tip', y=1.02)
plt.show()
sns.jointplot(x='total_bill', y='tip', data=df, kind='kde')
plt.suptitle('total bill v tip kde joint plot', y=1.02)
plt.show()
sns.pairplot(df[['total_bill', 'tip', 'size']])
plt.suptitle('pairplot-bill,tip,partysize', y=1.02)
plt.show()
sns.pairplot(x='day', y='total_bill', hue='sex', data=df)
plt.title("Average bill per day by gender")
plt.xlabel('day')
plt.ylabel('average bill')
plt.show()
sns.lmplot(x='total_bill', y='tip', data=df)
plt.title("total bill v tip")
plt.show()