import turtle
board = turtle.Turtle()
turtle.Screen().bgcolor("red")
board.color("black", "black")
board.begin_fill()
board.forward(200)
board.left(120)
board.forward(200)
board.left(120)
board.forward(200)
board.end_fill()
board.penup()
board.forward(200)

board.color("black", "yellow") 
board.left(120)
board.begin_fill()
board.pendown()
board.forward(200)
board.right(90)
board.forward(75)
board.right(90)
board.forward(200)
board.right(90)
board.forward(75)
board.end_fill()

board.penup()
board.forward(200)
board.left(90)
board.forward(100)
board.pendown

board.color("black", "blue")
board.begin_fill()
for _ in range(6):
    board.forward(100) 
    board.right(60) 
board.end_fill()    
turtle.done()